# Generated by Django 4.1.9 on 2023-06-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confidence',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(default='gmail', max_length=50),
        ),
    ]
