# Generated by Django 4.1.9 on 2023-06-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_alter_lead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lead',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(max_length=255),
        ),
    ]
