# Generated by Django 4.1.9 on 2023-06-07 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_alter_lead_company_alter_lead_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confidence',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.IntegerField(default=100),
        ),
    ]
