# Generated by Django 4.1.9 on 2023-06-08 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0005_alter_lead_confidence_alter_lead_estimated_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='estimated_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
