# Generated by Django 4.1.9 on 2023-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_alter_lead_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(blank=True, default='new', max_length=255),
        ),
    ]
