# Generated by Django 4.1.9 on 2023-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0008_alter_lead_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
